# Generated by Django 4.2.11 on 2026-05-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Project title", max_length=200)),
                (
                    "summary",
                    models.CharField(
                        help_text="One-sentence project summary", max_length=500
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed project description including business problem"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AI", "AI & Machine Learning"),
                            ("WEB", "Web Development"),
                            ("DATA", "Data Science"),
                            ("CYBERSECURITY", "Cybersecurity"),
                            ("CLOUD", "Cloud & DevOps"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Project category",
                        max_length=50,
                    ),
                ),
                (
                    "tools_used",
                    models.CharField(
                        help_text="Comma-separated list of tools and technologies",
                        max_length=500,
                    ),
                ),
                (
                    "key_features",
                    models.TextField(help_text="Key features and accomplishments"),
                ),
                (
                    "role_contribution",
                    models.TextField(
                        help_text="Your role and contribution to the project"
                    ),
                ),
                (
                    "challenges",
                    models.TextField(
                        help_text="Biggest challenges faced during the project"
                    ),
                ),
                (
                    "lessons_learned",
                    models.TextField(help_text="What you learned from the project"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Project screenshot or visual",
                        null=True,
                        upload_to="projects/",
                    ),
                ),
                (
                    "github_link",
                    models.URLField(
                        blank=True, help_text="Link to GitHub repository", null=True
                    ),
                ),
                (
                    "demo_link",
                    models.URLField(
                        blank=True,
                        help_text="Link to live demo or deployed project",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the project was added"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the project was last updated"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Display on home page as featured project",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order in which to display projects"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Projects",
                "ordering": ["-is_featured", "display_order", "-created_at"],
            },
        ),
    ]
