# Generated by Django 6.0.4 on 2026-05-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL slug (auto-generated from title)",
                unique=True,
            ),
        ),
    ]
