# Generated by Django 6.0.4 on 2026-05-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("AI", "AI & Machine Learning"),
                    ("WEB", "Web Development"),
                    ("DATA", "Data Science"),
                    ("CYBERSECURITY", "Cybersecurity"),
                    ("CLOUD", "Cloud & DevOps"),
                    ("AUTO", "Automation"),
                    ("DevOps", "DevOps/DevSecOps"),
                    ("Digital", "Digital Transformation"),
                    ("PM", "Project Management"),
                    ("Cyber", "Cybersecurity/Risk Management"),
                    ("OTHER", "Other"),
                ],
                help_text="Project category",
                max_length=50,
            ),
        ),
    ]
