# Generated by Django 6.0.4 on 2026-05-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("AI", "AI & Machine Learning"),
                    ("WEB", "Web Development"),
                    ("CYBER", "Cybersecurity"),
                    ("CLOUD", "Cloud & DevOps"),
                    ("DATA", "Data & Analytics"),
                    ("AUTO", "Automation"),
                    ("ML", "Machine Learning"),
                    ("OTHER", "Other"),
                ],
                help_text="Project category",
                max_length=50,
            ),
        ),
    ]
