# Generated by Django 6.0.4 on 2026-05-13 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "tagline",
                    models.CharField(
                        help_text="One-line summary shown on the Skills page.",
                        max_length=300,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Short paragraph shown on the home page expertise card. Falls back to tagline if blank.",
                    ),
                ),
                (
                    "accent",
                    models.CharField(
                        choices=[
                            ("violet", "Violet"),
                            ("indigo", "Indigo"),
                            ("blue", "Blue"),
                            ("sky", "Sky"),
                            ("purple", "Purple"),
                            ("fuchsia", "Fuchsia"),
                            ("rose", "Rose"),
                            ("emerald", "Emerald"),
                            ("green", "Green"),
                            ("amber", "Amber"),
                            ("red", "Red"),
                            ("gray", "Gray"),
                        ],
                        default="violet",
                        help_text="Tailwind color token used for the card's icon, chips, and accents.",
                        max_length=20,
                    ),
                ),
                (
                    "icon_svg_path",
                    models.TextField(
                        blank=True,
                        help_text='SVG path "d" attribute for the category icon (no <svg> wrapper).',
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                (
                    "show_on_home",
                    models.BooleanField(
                        default=True,
                        help_text="Display this category card in the home page Technical Expertise grid.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Skill categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "is_highlighted",
                    models.BooleanField(
                        default=False,
                        help_text="Show this skill as a chip on the home page category card (top picks).",
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="core.skillcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
                "unique_together": {("category", "name")},
            },
        ),
    ]
