# Generated by Django 6.0.4 on 2026-05-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("issuer", models.CharField(blank=True, max_length=200)),
                (
                    "earned",
                    models.CharField(
                        blank=True,
                        help_text='Date or status, e.g. "April 2026" or "In progress".',
                        max_length=80,
                    ),
                ),
                ("is_in_progress", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["is_in_progress", "display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=200)),
                ("school", models.CharField(max_length=200)),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Expected December 2026".',
                        max_length=80,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "period",
                    models.CharField(
                        help_text='Human-readable period, e.g. "2023 — Present".',
                        max_length=80,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Short paragraph shown on the About timeline.",
                    ),
                ),
                (
                    "highlights",
                    models.TextField(
                        blank=True,
                        help_text="One highlight per line. Shown as bullet list on resume page.",
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "-is_current"],
            },
        ),
    ]
