# Generated by Django 6.0.4 on 2026-05-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="author",
            field=models.CharField(default="Stephen Sowah", max_length=120),
        ),
    ]
